---
# The following step will copy the httpd rpm file from the files folder to /tmp folder on remote server
# the version of httpd file must be set on here using the command, adding the quote right below the next name sentence:
# vars:
#    http_rpm_file_version: "<desired version>"

- name: Copy HTTPD RPM file to /tmp folder
  copy:
    src: textkernel_eliel/files/httpd-{{ http_rpm_file_version }}.el7.centos.x86_64.rpm
    dest: /tmp/httpd-{{ http_rpm_file_version }}.el7.centos.x86_64.rpm

  # install HTTPD RPM file using yum and root permissions
- name: Install HTTPD RPM File
  yum:
    name: /tmp/httpd-{{ http_rpm_file_version }}.el7.centos.x86_64.rpm
    state: present
    allow_downgrade: yes

- name: Set the httpd properties defined on defaults/main.yml if the user specifies the listen ip
  command: sed -i "s/Listen 80/Listen {{ httpd_listen_ip }}:{{ httpd_listen }}/g" /etc/httpd/conf/httpd.conf
  when: '"{{ httpd_listen_ip }}" not in "*"'

  # set httpd to be started automatically and start the service
- name: Start HTTPD service automatically
  service: 
    name: httpd
    enabled: yes
    state: started